adds checks for icons and toc attributes
redhataccess/pantheon-cmd pull request #36
Opened 2021-09-24 23:47 UTC by Levi-Leah

2021-09-24 23:48 UTC, Levi-Leah commented
@adahms 
this should throw errors for icons and toc attributes

2021-09-26 23:33 UTC, adahms approved these changes
Thanks @Levi-Leah - I can confirm that the icons and toc tests are working as expected.

One question - in case someone includes these in their pantheon2.yml file, should we check that as well for any references?

If you'd like to go ahead and merge this, we can address that question in a separate issue.

2021-09-26 23:37 UTC, Levi-Leah commented
@adahms 
Can you clarify about the inclusion of these attributes in the pv2.yml? Do you mean if files that contain these attributes are part of pv2.yml?

2021-09-26 23:41 UTC, adahms commented
@Levi-Leah - Gah, sorry - not the pantheon2.yml file, but the attributes file. ><

2021-09-26 23:48 UTC, Levi-Leah commented
@adahms
right now I don’t parse attributes file for anything related to the checks but it should be easy to set up. That being said, if none of the modules/assemblies actually call for these attributes, would flagging it in the attributes file be necessary? Would having in attributes file break smth?

2021-09-26 23:53 UTC, adahms commented
@Levi-Leah - very true. Perhaps the only thing I'm worried about are these attributes that change the structure of the document. Anything a user specifies in the pantheon2.yml file gets injected into every assembly and module, meaning that if a user specifies the 'toc' attribute there, everything gets it.

2021-09-27 16:13 UTC, Levi-Leah commented
@adahms 
I added toc/icons validation for the attributes file. please take a look when you get the time

2021-09-28 00:29 UTC, adahms requested changes
Hey @Levi-Leah - PCMD is now detecting cases of these attributes in the pantheon2.yml file. Added a comment about some double reporting in results, otherwise, everything's working as expected.

2021-09-28 14:13 UTC, Levi-Leah commented on PantheonCMD/pcvalidator.py
> +            icons_check(report, stripped, path)
fixed

2021-09-28 14:14 UTC, merged